apiVersion: v1
kind: ReplicationController
metadata:
  name: elasticsearch-logging-v1
  namespace: kube-system
  labels:
    k8s-app: elasticsearch-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1 # 2
  selector:
    k8s-app: elasticsearch-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - env:
        - name: NODE_MASTER
          value: "true"
        - name: NODE_DATA
          value: "true"
        - name: HTTP_PORT
          value: "9200"
        - name: TRANSPORT_PORT
          value: "9300"
        image: gcr.io/google_containers/elasticsearch:1.9
        imagePullPolicy: IfNotPresent
        name: elasticsearch-logging         
        # resources:
          # keep request = limit to keep this container in guaranteed class
        #   limits:
        #     cpu: 100m
        #   requests:
        #     cpu: 100m
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: es-persistent-storage
          mountPath: /data
        - name: es-run
          mountPath: /run.sh
      volumes:
      - name: es-persistent-storage
        emptyDir: {}
      - name: es-run
        hostPath:
          path: /data/src/github.com/stackdocker/k8s-logging-paas/kubernetes-project/cluster/addons/fluentd-elasticsearch/run.sh
