#!/bin/bash
#export ELASTICSEARCH_URL="http://${ELASTICSEARCH_LOGGING_SERVICE_HOST}:${ELASTICSEARCH_LOGGING_SERVICE_PORT}"
echo $ELASTICSEARCH_URL
export KIBANA_ES_URL=$ELASTICSEARCH_URL
/kibana-4.0.2-linux-x64/bin/kibana -e ${KIBANA_ES_URL}
