apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "elasticsearch-client"
spec:
  replicas: 1
  selector:
    component: "elasticsearch"
    type: "client"
    provider: "fabric8"
  template:
    metadata:
      labels:
        component: "elasticsearch"
        type: "client"
        provider: "fabric8"
    spec:
      serviceAccount: elasticsearch
      serviceAccountName: elasticsearch
      containers:
      - env:
        - name: "SERVICE"
          value: "elasticsearch-cluster"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "NODE_DATA"
          value: "false"
        - name: "NODE_MASTER"
          value: "false"
        image: "fabric8/elasticsearch-k8s:2.3.3"
        imagePullPolicy: IfNotPresent
        name: "elasticsearch"
        ports:
        - containerPort: 9200
          name: "http"
        - containerPort: 9300
          name: "transport"
