apiVersion: "v1"
kind: "ReplicationController"
metadata:
  name: "elasticsearch-master"
spec:
  replicas: 1
  selector:
    component: "elasticsearch"
    type: "master"
    provider: "fabric8"
  template:
    metadata:
      labels:
        component: "elasticsearch"
        type: "master"
        provider: "fabric8"
    spec:
      serviceAccount: elasticsearch
      serviceAccountName: elasticsearch
      containers:
      - env:
        - name: "SERVICE"
          value: "elasticsearch-cluster"
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: "NODE_DATA"
          value: "false"
        image: "fabric8/elasticsearch-k8s:2.3.3"
        imagePullPolicy: IfNotPresent
        name: "elasticsearch"
        ports:
        - containerPort: 9300
          name: "transport"
        volumeMounts:
        - name: external-config
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
        - name: external-run
          mountPath: /docker-entrypoint.sh
      volumes:
      - name: external-config
        hostPath:
          path: /data/src/github.com/stackdocker/k8s-logging-paas/elasticsearch1.yml
      - name: external-run
        hostPath:
          path: /data/src/github.com/stackdocker/k8s-logging-paas/elasticsearch-master-run.sh
