--- 
apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch"
spec:
  ports:
  - nodePort: 32124
    port: 9200
    targetPort: "http"
  selector:
    component: "elasticsearch"
    type: "client"
    provider: "fabric8"
  type: "NodePort" # "LoadBalancer"
--- 
apiVersion: "v1"
kind: "Service"
metadata:
  name: "elasticsearch-cluster"
spec:
  clusterIP: "None"
  ports:
  - port: 9300
    targetPort: 9300
  selector:
    provider: "fabric8"
    component: "elasticsearch"
