apiVersion: v1
kind: ReplicationController
metadata:
  name: kibana
  namespace: default
  labels:
    component: elk
    role: kibana
spec:
  replicas: 1
  selector:
    component: elk
    role: kibana
  template:
    metadata:
      labels:
        component: elk
        role: kibana
    spec:
      serviceAccount: elk
      containers:
      - name: kibana
        image: fabric8/kibana4:v4.5.1
        imagePullPolicy: IfNotPresent
        env:
        - name: ELASTICSEARCH_SERVICE_NAME
          value: ELASTICSEARCH
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
