apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash-logging-v1
  namespace: kube-system
  labels:
    k8s-app: logstash-logging
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: logstash-logging
    version: v1
  template:
    metadata:
      labels:
        k8s-app: logstash-logging
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: logstash-logging
        image: tangfeixiong/logstash:2.3.2-log4j # docker.io/pires/logstash # docker.io/fabric8/logstash
        imagePullPolicy: IfNotPresent
        # resources:
          # keep request = limit to keep this container in guaranteed class
        #   limits:
        #     cpu: 100m
        #   requests:
        #     cpu: 100m
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
        command: 
        - "/logstash/bin/logstash"
        # - "--quiet" 
        - "-f"
        - "/logstash/config/logstash.conf"
        ports:
        - containerPort: 4560
          name: log4j
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /logstash/config/logstash.conf
      volumes:
      - name: config
        hostPath: 
          path: /data/src/github.com/stackdocker/k8s-logging-paas/logstash-log4j.conf
